<div class="repository">
  <h3><a href="{{url}}">{{name}}</a></h3>

  <ul class="tabs">
    <li id="tab_current">
      <h5><a href="#!/{{name}}">Current</a></h5>
      <div class="tab"></div>
    </li>
    <li id="tab_history">
      <h5><a href="#!/{{name}}/builds">Build History</a></h5>
      <div class="tab"></div>
    </li>
    <li id="tab_build">
      <h5><a href="">Build #</a></h5>
      <div></div>
    </li>
  </ul>
</div>
