source 'http://rubygems.org'

gem 'rails', '3.0.3'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'thin'
gem 'SystemTimer'
gem 'resque'
gem 'resque-meta'
gem 'minimal'
gem 'em-websocket'
# gem 'socky-client-rails'
# gem 'em-redis'

group :test do
  gem 'webrat'
  gem 'database_cleaner'
  gem 'cucumber-rails'
  gem 'cucumber'
  gem 'jsonpath'
  gem 'test_declarative'
  gem 'launchy'
  gem 'ruby-debug'
  gem 'mocha'
  gem 'web-socket-ruby'
end
