defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # The server defaults to notice.
  min_messages: warning

development:
  <<: *defaults
  database: travis_development

production:
  <<: *defaults
  database: travis_production

jasmine:
  <<: *defaults
  database: travis_jasmine

test:
  <<: *defaults
  database: travis_test
