<dl class="summary clearfix">
  <dt>Build</dt>
  <dd class="number"><a href="/#!/builds/{{id}}">{{number}}</a></dd>
  <dt>Commit</dt>
  <dd class="commit-hash">{{commit}}</dd>
  <dt>Message</dt>
  <dd class="commit-message">{{message}}</dd>
  <dt>Duration</dt>
  <dd class="duration">{{duration}}</dd>
  <dt class="finished_at_label">Finished</dt>
  <dd class="finished_at timeago" title="{{finished_at}}"></d>
  <dt class="eta_label">ETA</dt>
  <dd class="eta timeago" title="{{eta}}"></d>
</dl>
