<div id="welcome">
  <h4>Welcome to Travis!</h4>
  <p>
    To add a project to Travis, create a <code>.travis.yml</code> file in the project's root. <a href="https://github.com/travis-ci/travis-ci/wiki/.travis.yml-options">There are lots of different options</a>.
  </p>
  <p>
    Then using the token from your <a href="/profile">profile page</a>, add the Travis post-recieve hook to your project on Github.
  </p>
</div>
